### ISSUE TITLE
Can't download via pod only, must specified github url

### ISSUE THREAD

**Issue by Black-Colt** [vrutberg/VRPicker#3]
Like the title said, in order to add it to Podfile you must specified github url like:
pod 'VRPicker', :git =>'https://github.com/vrutberg/VRPicker'

**Comment by vrutberg** [comment]
What does your Podfile look like? What kind of error message do you get when it's not working?

**Comment by Black-Colt** [comment]
"Unable to find a specification in CocoaPods"

When I specified the git url its ok.

http://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods

**Comment by vrutberg** [comment]
Have you tried running `pod repo update master`?

**Comment by vrutberg** [comment]
If yes, and that still doesn't fix the issue, could you paste a copy of your Podfile here?

**Comment by Black-Colt** [comment]
Worked, thanks!

**Comment by vrutberg** [comment]
Great!
